In [ ]:
#imports
import os
import pandas as pd
import numpy as np
import random
random.seed(1)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving brfss2020.csv to brfss2020.csv

In [ ]:
import io
brfss_2020_dataset = pd.read_csv(io.BytesIO(uploaded['brfss2020.csv']))
# Dataset is now stored in a Pandas Dataframe

In [ ]:
brfss_2020_dataset.shape

(401958, 279)

In [ ]:
pd.set_option('display.max_columns', 500)
brfss_2020_dataset.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHONE,LADULT1,COLGSEX,NUMADULT,LANDSEX,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,EXERANY2,SLEPTIM1,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD2,HAVARTH4,ADDEPEV3,CHCKDNY2,DIABETE4,DIABAGE3,LASTDEN4,RMVTETH4,MARITAL,EDUCA,RENTHOM1,NUMHHOL3,NUMPHON3,CPDEMO1B,VETERAN3,EMPLOY1,CHILDREN,INCOME2,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,SHINGLE2,PNEUVAC4,FALL12MN,FALLINJ4,SEATBELT,DRNKDRI2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PCPSAAD3,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,COLNSCPY,COLNTEST,SIGMSCPY,SIGMTEST,BLDSTOL1,LSTBLDS4,STOOLDNA,SDNATEST,VIRCOLON,VCLNTEST,HIVTST7,HIVTSTD3,HIVRISK5,PDIABTST,PREDIAB1,INSULIN1,BLDSUGAR,FEETCHK3,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM1,DIABEYE,DIABEDU,TOLDCFS,HAVECFS,WORKCFS,TOLDHEPC,TRETHEPC,PRIRHEPC,HAVEHEPC,HAVEHEPB,MEDSHEPB,HLTHCVR1,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ECIGARET,ECIGNOW,MARIJAN1,USEMRJN2,RSNMRJN1,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSCN,CNCRDIFF,CNCRAGE,CNCRTYP1,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PCPSADE1,PCDMDEC1,HPVADVC4,HPVADSHT,TETANUS1,IMFVPLA1,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HCVU651,_TOTINDA,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_EXTETH3,_ALTETH3,_DENVST3,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWK1,_RFDRHV7,_FLSHOT7,_PNEUMO3,_RFSEAT2,_RFSEAT3,_DRNKDRV,_RFMAM22,_MAM5023,_RFPAP35,_RFPSA23,_CLNSCPY,_SGMSCPY,_SGMS10Y,_RFBLDS4,_STOLDNA,_VIRCOLN,_SBONTIM,_CRCREC1,_AIDTST4
0,1.0,1.0,1042020,1,4,2020,1100.0,2020000001,2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,30.0,3.0,2.0,3.0,1.0,4.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,35.0,1.0,2.0,2.0,6.0,1.0,2.0,NaN,1.0,2.0,4.0,88.0,1.0,NaN,106.0,507.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,1.0,3.0,1.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0,21994.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,1.0,0.465411,460.002849,284.335672,1.0,2.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,67.0,170.0,4808.0,1660.0,1.0,1.0,1.0,4.0,1.0,1.0,2.0,2.0,0.0,1.0,0.0,1.0,NaN,NaN,1.0,1.0,9.0,2.0,2.0,NaN,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
1,1.0,1.0,2072020,2,7,2020,1200.0,2020000002,2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,NaN,1.0,1.0,3.0,6.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,170.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,2.0,NaN,NaN,NaN,NaN,1.0,0.465411,460.002849,171.283329,1.0,1.0,1.0,9.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,65.0,6.0,64.0,163.0,7711.0,2918.0,3.0,2.0,1.0,4.0,9.0,9.0,9.0,9.0,900.0,9.0,99900.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
2,1.0,1.0,1232020,1,23,2020,1100.0,2020000003,2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,7.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,7777.0,508.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11012.0,279.748901,1.0,279.748901,2.0,NaN,NaN,NaN,NaN,1.0,0.465411,1847.859110,1334.368860,1.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,3.0,1.0,9.0,9.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,65.0,6.0,68.0,173.0,NaN,NaN,NaN,9.0,1.0,3.0,5.0,4.0,1.0,2.0,0.0,1.0,0.0,1.0,1.0,2.0,1.0,1.0,9.0,1.0,1.0,1.0,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0
3,1.0,1.0,1092020,1,9,2020,1100.0,2020000004,2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,2.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,1.0,3.0,4.0,1.0,9.0,NaN,9.0,2.0,5.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,2.0,NaN,1.0,7.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,9.0,NaN,1472.417320,1297.486620,1.0,1.0,1.0,9.0,2.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,9.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,2.0,9.0,4.0,1.0,2.0,0.0,1.0,0.0,1.0,2.0,2.0,1.0,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,1.0,1.0,1042020,1,4,2020,1100.0,2020000005,2.020000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,8.0,3.0,6.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,77.0,NaN,126.0,506.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,1.0,2.0,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,NaN,7.0,NaN,7.0,NaN,2.0,NaN,7.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,69.640207,1.0,69.640207,1.0,NaN,NaN,NaN,NaN,9.0,NaN,1472.417320,454.815127,1.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,9.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,66.0,168.0,5715.0,2034.0,2.0,1.0,1.0,4.0,9.0,4.0,1.0,2.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [ ]:
brfss_df_selected = brfss_2020_dataset[['DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'CPDEMO1B', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME2', 'PREGNANT', 'SMOKE100', 'AVEDRNK3', 'ACEDEPRS', 'BIRTHSEX', 'SOMALE', 'SOFEMALE', 'TRNSGNDR', 'ACEDRINK', 'ACEDRUGS', 'ACEDIVRC', 'QSTLANG', '_URBSTAT', 'HLTHPLN1']]

In [ ]:
brfss_df_selected.shape

(401958, 23)

In [ ]:
brfss_df_selected.head()

,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1B,VETERAN3,EMPLOY1,CHILDREN,INCOME2,PREGNANT,SMOKE100,AVEDRNK3,ACEDEPRS,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,ACEDRINK,ACEDRUGS,ACEDIVRC,QSTLANG,_URBSTAT,HLTHPLN1
0,1.0,2.0,6.0,1.0,1.0,2.0,4.0,88.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0
1,3.0,3.0,6.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
2,3.0,1.0,5.0,1.0,1.0,2.0,7.0,88.0,7.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0
3,3.0,3.0,4.0,1.0,9.0,2.0,5.0,88.0,99.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0
4,3.0,3.0,6.0,2.0,8.0,2.0,7.0,88.0,77.0,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0

In [ ]:
# DIABETE4
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([ 1.,  0., nan])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.MARITAL != 9]
brfss_df_selected.MARITAL.unique()

array([ 2.,  3.,  1.,  4.,  5.,  6., nan])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([ 6.,  5.,  4.,  2.,  3., nan,  1.])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.RENTHOM1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.RENTHOM1 != 7]
brfss_df_selected.RENTHOM1.unique()

array([ 1.,  2.,  3., nan])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.CPDEMO1B != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CPDEMO1B != 7]
brfss_df_selected.CPDEMO1B.unique()

array([ 1.,  8.,  2.,  3.,  4.,  6., nan,  5.])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.VETERAN3 != 9]
brfss_df_selected.VETERAN3.unique()

array([ 2.,  1., nan,  7.])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EMPLOY1 != 9]
brfss_df_selected.EMPLOY1.unique()

array([ 4.,  7.,  8.,  1.,  5.,  3., nan,  6.,  2.])

In [ ]:
brfss_df_selected['CHILDREN'] = brfss_df_selected['CHILDREN'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHILDREN != 99]
brfss_df_selected.CHILDREN.unique()

array([ 0.,  2.,  1., nan,  3.,  4.,  6.,  7.,  5.,  9.,  8., 20., 10.,
       15., 14., 23., 11., 24., 81., 82., 12., 13., 22., 19., 21., 77.,
       16.])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 99]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 77]
brfss_df_selected.INCOME2.unique()

array([ 1.,  7.,  5.,  6.,  4., nan,  2.,  8.,  3.])

In [ ]:
brfss_df_selected['PREGNANT'] = brfss_df_selected['PREGNANT'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PREGNANT != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PREGNANT != 7]
brfss_df_selected.PREGNANT.unique()

array([nan,  0.,  1.])

In [ ]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([ 1.,  0., nan])

In [ ]:
brfss_df_selected['AVEDRNK3'] = brfss_df_selected['AVEDRNK3'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.AVEDRNK3 != 99]
brfss_df_selected = brfss_df_selected[brfss_df_selected.AVEDRNK3 != 77]
brfss_df_selected.AVEDRNK3.unique()

array([nan,  1.,  2.,  3.,  0.,  4., 10.,  8.,  6.,  7.,  5., 20., 12.,
       30., 15., 40., 25., 13.,  9., 18., 16., 11., 50., 24., 48., 60.,
       70., 27., 35., 56., 14., 64., 76., 45., 17., 47., 26., 51., 63.,
       21., 36., 32., 33., 54., 23., 75., 57., 66., 22., 53., 28., 34.,
       37., 38., 41.])

In [ ]:
brfss_df_selected['ACEDEPRS'] = brfss_df_selected['ACEDEPRS'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDEPRS != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDEPRS != 9]
brfss_df_selected.ACEDEPRS.unique()

array([ 1.,  0., nan])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.BIRTHSEX != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.BIRTHSEX != 7]
brfss_df_selected.BIRTHSEX.unique()

array([nan,  2.,  1.])

In [ ]:
brfss_df_selected['SOMALE'] = brfss_df_selected['SOMALE'].replace({2:0, 3:2})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOMALE != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOMALE != 9]
brfss_df_selected.SOMALE.unique()

array([nan,  0.,  2.,  4.,  1.])

In [ ]:
brfss_df_selected['SOFEMALE'] = brfss_df_selected['SOFEMALE'].replace({2:0, 3:2})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOFEMALE != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SOFEMALE != 9]
brfss_df_selected.SOFEMALE.unique()

array([nan,  4.,  0.,  1.,  2.])

In [ ]:
brfss_df_selected['TRNSGNDR'] = brfss_df_selected['TRNSGNDR'].replace({4:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TRNSGNDR != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TRNSGNDR != 9]
brfss_df_selected.TRNSGNDR.unique()

array([nan,  0.,  3.,  2.,  1.])

In [ ]:
brfss_df_selected['ACEDRINK'] = brfss_df_selected['ACEDRINK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRINK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRINK != 9]
brfss_df_selected.ACEDRINK.unique()

array([ 1.,  0., nan])

In [ ]:
brfss_df_selected['ACEDRUGS'] = brfss_df_selected['ACEDRUGS'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRUGS != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDRUGS != 9]
brfss_df_selected.ACEDRUGS.unique()

array([ 1.,  0., nan])

In [ ]:
brfss_df_selected['ACEDIVRC'] = brfss_df_selected['ACEDIVRC'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDIVRC != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ACEDIVRC != 9]
brfss_df_selected.ACEDIVRC.unique()

array([ 1.,  0., nan,  8.])

In [ ]:
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 9]
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 7]
brfss_df_selected.HLTHPLN1.unique()

array([ 2.,  1., nan])

In [ ]:
brfss_df_selected.shape

(310414, 23)

In [ ]:
brfss_df_selected.head()

,DIABETE4,MARITAL,EDUCA,RENTHOM1,CPDEMO1B,VETERAN3,EMPLOY1,CHILDREN,INCOME2,PREGNANT,SMOKE100,AVEDRNK3,ACEDEPRS,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,ACEDRINK,ACEDRUGS,ACEDIVRC,QSTLANG,_URBSTAT,HLTHPLN1
0,1.0,2.0,6.0,1.0,1.0,2.0,4.0,0.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0
2,0.0,1.0,5.0,1.0,1.0,2.0,7.0,0.0,7.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0
5,1.0,4.0,4.0,3.0,1.0,2.0,8.0,0.0,5.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0
6,0.0,1.0,4.0,1.0,2.0,2.0,7.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
7,1.0,1.0,4.0,1.0,1.0,2.0,7.0,0.0,5.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [ ]:
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    263929
1.0     46479
dtype: int64

In [ ]:
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', 'MARITAL': 'Marital Status', 'EDUCA':'Education Level', 'RENTHOM1':'Own or Rent Home', 'CPDEMO1B':'Has Phone', 'SMOKE100':'Smoker', 'VETERAN3':'Veteran', 'EMPLOY1':'Employment Status', 'CHILDREN':'Children', 'INCOME2':'Household Income', 'PREGNANT':"Pregnant", 'AVEDRNK3':'Alcohol Consumption', 'HLTHPLN1':'HealthCare', 'ACEDEPRS':'Depressed', 'BIRTHSEX':'Sex', 'SOMALE':'Male Sexual Orientation', 'SOFEMALE':'Female Sexual Orientation', 'TRNSGNDR':'Transgender', 'ACEDRINK':'DrunkFamily', 'ACEDRUGS':'DrugsInFamily', 'ACEDIVRC':'Divorced Parents', 'QSTLANG':'Primary Language', '_URBSTAT':'Urban or Rural'})

In [ ]:
brfss.head()

,Diabetes,Marital Status,Education Level,Own or Rent Home,Has Phone,Veteran,Employment Status,Children,Household Income,Pregnant,Smoker,Alcohol Consumption,Depressed,Sex,Male Sexual Orientation,Female Sexual Orientation,Transgender,DrunkFamily,DrugsInFamily,Divorced Parents,Primary Language,Urban or Rural,HealthCare
0,1.0,2.0,6.0,1.0,1.0,2.0,4.0,0.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0
2,0.0,1.0,5.0,1.0,1.0,2.0,7.0,0.0,7.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0
5,1.0,4.0,4.0,3.0,1.0,2.0,8.0,0.0,5.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0
6,0.0,1.0,4.0,1.0,2.0,2.0,7.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
7,1.0,1.0,4.0,1.0,1.0,2.0,7.0,0.0,5.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [ ]:
brfss.shape

(310414, 23)

In [ ]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    263929
1.0     46479
dtype: int64

In [ ]:
from google.colab import files
brfss.to_csv('cleanData.csv', encoding = 'utf-8-sig') 
files.download('cleanData.csv')

In [147]:
#Copy old table to new one.
brfss_binary = brfss
#Change the column name to Diabetes_binary
brfss_binary = brfss_binary.rename(columns = {'Diabetes': 'Diabetes_binary'})
brfss_binary.Diabetes_binary.unique()

array([ 1.,  0., nan])

In [148]:
brfss_binary.head()

,Diabetes_binary,Marital Status,Education Level,Own or Rent Home,Has Phone,Veteran,Employment Status,Children,Household Income,Pregnant,Smoker,Alcohol Consumption,Depressed,Sex,Male Sexual Orientation,Female Sexual Orientation,Transgender,DrunkFamily,DrugsInFamily,Divorced Parents,Primary Language,Urban or Rural,HealthCare
0,1.0,2.0,6.0,1.0,1.0,2.0,4.0,0.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0
2,0.0,1.0,5.0,1.0,1.0,2.0,7.0,0.0,7.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0
5,1.0,4.0,4.0,3.0,1.0,2.0,8.0,0.0,5.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0
6,0.0,1.0,4.0,1.0,2.0,2.0,7.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
7,1.0,1.0,4.0,1.0,1.0,2.0,7.0,0.0,5.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [149]:
brfss_binary.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    263929
1.0     46479
dtype: int64

In [151]:
#Separate the 0(No Diabetes) and 1&2(Pre-diabetes and Diabetes)
#Get the 1s
is1 = brfss_binary['Diabetes_binary'] == 1
brfss_5050_1 = brfss_binary[is1]

#Get the 0s
is0 = brfss_binary['Diabetes_binary'] == 0
brfss_5050_0 = brfss_binary[is0] 

#Select the 39977 random cases from the 0 (non-diabetes group). we already have 35346 cases from the diabetes risk group
brfss_5050_0_rand1 = brfss_5050_0.take(np.random.permutation(len(brfss_5050_0))[:46479])

#Append the 39977 1s to the 39977 randomly selected 0s
brfss_5050 = brfss_5050_0_rand1.append(brfss_5050_1, ignore_index = True)

<ipython-input-151-222151861789>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  brfss_5050 = brfss_5050_0_rand1.append(brfss_5050_1, ignore_index = True)

In [152]:
#Check that it worked. Now we have a dataset of 79,954 rows that is equally balanced with 50% 1 and 50% 0 for the target variable Diabetes_binary
brfss_5050.head()

,Diabetes_binary,Marital Status,Education Level,Own or Rent Home,Has Phone,Veteran,Employment Status,Children,Household Income,Pregnant,Smoker,Alcohol Consumption,Depressed,Sex,Male Sexual Orientation,Female Sexual Orientation,Transgender,DrunkFamily,DrugsInFamily,Divorced Parents,Primary Language,Urban or Rural,HealthCare
0,0.0,1.0,4.0,1.0,1.0,2.0,1.0,1.0,8.0,NaN,0.0,3.0,NaN,1.0,0.0,NaN,0.0,NaN,NaN,NaN,1.0,1.0,1.0
1,0.0,1.0,5.0,1.0,1.0,2.0,1.0,0.0,6.0,NaN,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0
2,0.0,1.0,6.0,1.0,3.0,2.0,7.0,0.0,7.0,NaN,0.0,2.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
3,0.0,1.0,6.0,1.0,1.0,2.0,7.0,0.0,8.0,NaN,0.0,1.0,NaN,2.0,NaN,0.0,0.0,NaN,NaN,NaN,1.0,1.0,1.0
4,0.0,6.0,3.0,2.0,1.0,2.0,1.0,2.0,3.0,0.0,0.0,1.0,0.0,2.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0

In [153]:
brfss_5050.tail()

,Diabetes_binary,Marital Status,Education Level,Own or Rent Home,Has Phone,Veteran,Employment Status,Children,Household Income,Pregnant,Smoker,Alcohol Consumption,Depressed,Sex,Male Sexual Orientation,Female Sexual Orientation,Transgender,DrunkFamily,DrugsInFamily,Divorced Parents,Primary Language,Urban or Rural,HealthCare
92953,1.0,5.0,6.0,1.0,2.0,2.0,7.0,0.0,5.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0
92954,1.0,1.0,6.0,1.0,1.0,2.0,7.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0
92955,1.0,2.0,5.0,1.0,1.0,2.0,1.0,0.0,4.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0
92956,1.0,3.0,5.0,3.0,1.0,2.0,7.0,0.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0
92957,1.0,1.0,6.0,1.0,1.0,2.0,8.0,0.0,5.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0

In [154]:
brfss_5050.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    46479
1.0    46479
dtype: int64

In [155]:
print(f'brfss_5050={brfss_5050.shape}',f'brfss_binary={brfss_binary.shape}')

brfss_5050=(92958, 23) brfss_binary=(310414, 23)

In [156]:
from google.colab import files
brfss.to_csv('binaryData.csv', encoding = 'utf-8-sig') 
files.download('binaryData.csv')